insert into AEROPORTS (ID, NOM) values ('AGA','Maroc - Agadir');
insert into AEROPORTS (ID, NOM) values ('ALG','Algérie - Alger');
insert into AEROPORTS (ID, NOM) values ('BKO','Mali - Bamako');
insert into AEROPORTS (ID, NOM) values ('BIQ','France - Biarritz');
insert into AEROPORTS (ID, NOM) values ('BRU','Belgique - Bruxelles');
insert into AEROPORTS (ID, NOM) values ('CDG','France - Paris (CDG)');
insert into AEROPORTS (ID, NOM) values ('CMN','Maroc - Casablanca');
insert into AEROPORTS (ID, NOM) values ('RAK','Maroc - Marrakech');
insert into AEROPORTS (ID, NOM) values ('DFW','Etats-Unis - Dallas');
insert into AEROPORTS (ID, NOM) values ('GVA','Suisse - Genève');
insert into AEROPORTS (ID, NOM) values ('HNL','Etats-Unis - Honolulu');
insert into AEROPORTS (ID, NOM) values ('HND','Japon - Tokyo');
insert into AEROPORTS (ID, NOM) values ('KIX','Japon - Osaka');
insert into AEROPORTS (ID, NOM) values ('LAI','France - Lannion');
insert into AEROPORTS (ID, NOM) values ('LAX','Etats-Unis - Los Angeles');
insert into AEROPORTS (ID, NOM) values ('LYS','France - Lyon');
insert into AEROPORTS (ID, NOM) values ('MSP','Etats-Unis - Minneapolis');
insert into AEROPORTS (ID, NOM) values ('MRS','France - Marseille');
insert into AEROPORTS (ID, NOM) values ('PEK','Chine - Pékin');
insert into AEROPORTS (ID, NOM) values ('NCE','France - Nice');
insert into AEROPORTS (ID, NOM) values ('ORY','France - Orly');
insert into AEROPORTS (ID, NOM) values ('PPT','Polynésie Française - Papeete');
insert into AEROPORTS (ID, NOM) values ('TXL','Allemagne - Berlin (Tegel)');
insert into AEROPORTS (ID, NOM) values ('SAN','Etats-Unis - San Diego');
insert into AEROPORTS (ID, NOM) values ('SXF','Allemagne - Berlin');
insert into AEROPORTS (ID, NOM) values ('XPG','France - Paris (Gare du nord)');
insert into AEROPORTS (ID, NOM) values ('YQB','Canada - Québec');
insert into AEROPORTS (ID, NOM) values ('YYZ','Canada - Toronto');
insert into AEROPORTS (ID, NOM) values ('PVG','Chine - Shangai');
insert into AEROPORTS (ID, NOM) values ('SYD','Australie - Sydney');
insert into AEROPORTS (ID, NOM) values ('IAH','Etats-Unis - Houston Texas');
insert into AEROPORTS (ID, NOM) values ('JFK','Etats-Unis - New York');
insert into AEROPORTS (ID, NOM) values ('TLS','France - Toulouse');
insert into AEROPORTS (ID, NOM) values ('RNS','France - Rennes');